version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: itq-postgres
    environment:
      POSTGRES_DB: itqdb
      POSTGRES_USER: itquser
      POSTGRES_PASSWORD: itqpass
    ports:
      - "5432:5432"
    volumes:
      - itq-postgres-data:/var/lib/postgresql/data

volumes:
  itq-postgres-data:

